# Generated by Django 6.0.1 on 2026-02-17 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_job_notifications', models.BooleanField(default=True)),
                ('email_event_notifications', models.BooleanField(default=True)),
                ('email_comment_notifications', models.BooleanField(default=True)),
                ('email_connection_requests', models.BooleanField(default=True)),
                ('email_announcements', models.BooleanField(default=True)),
                ('email_weekly_digest', models.BooleanField(default=True)),
                ('inapp_job_notifications', models.BooleanField(default=True)),
                ('inapp_event_notifications', models.BooleanField(default=True)),
                ('inapp_comment_notifications', models.BooleanField(default=True)),
                ('inapp_connection_requests', models.BooleanField(default=True)),
                ('inapp_announcements', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('job', 'Job Opportunity'), ('event', 'Event'), ('comment', 'Comment'), ('like', 'Like'), ('connection', 'Connection Request'), ('message', 'Message'), ('announcement', 'Announcement'), ('verification', 'Profile Verification'), ('blog', 'Blog Post')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('related_id', models.CharField(blank=True, max_length=100)),
                ('related_type', models.CharField(blank=True, max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('is_emailed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
