# Generated by Django 6.0.1 on 2026-02-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('seminar', 'Seminar'), ('webinar', 'Webinar'), ('conference', 'Conference'), ('meetup', 'Meetup'), ('networking', 'Networking'), ('other', 'Other')], default='workshop', max_length=20),
        ),
    ]
