# Generated by Django 6.0.1 on 2026-02-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_hierarchical_relationships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('cse', 'Computer Science & Engineering'), ('ece', 'Electronics & Communication Engineering'), ('eee', 'Electrical & Electronics Engineering'), ('mech', 'Mechanical Engineering'), ('civil', 'Civil Engineering'), ('it', 'Information Technology')], max_length=10, null=True),
        ),
    ]
