# Generated by Django 6.0.1 on 2026-02-28 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_job_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Must remove the FK (job) first — it owns the job_id column.
        # Only then can we add the new job_id CharField without a column conflict.
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='job',
        ),
        migrations.AddField(
            model_name='savedjob',
            name='job_id',
            field=models.CharField(blank=True, default='', help_text='MongoDB Job ObjectId or Django Job ID', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('user', 'job_id')},
        ),
    ]
